# Generated by Django 4.2.4 on 2023-10-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_mobile',
            new_name='mobile',
        ),
    ]
